all:
	gcc server.c -g -o /tmp/server -pthread -Wall
	gcc client.c -g -o /tmp/client -pthread -Wall
server:
	gcc server.c -g -o /tmp/server -pthread -Wall
client:
	gcc client.c -g -o /tmp/client -pthread -Wall
